export default {
  PLAYER_STARTING: 'PLAYER STARTING',
  PLAYER_READY: 'PLAYER READY',
  PLAYER_PLAYING: 'PLAYER PLAYING',
  CPU_PLAYING: 'CPU PLAYING',
  GAME_ENDED: 'GAME ENDED',
  PLAYER_SURRENDERED: 'PLAYER_SURRENDERED'
};
